//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2018 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2018.InputResource", typeof(InputResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bqlpzruexkszyahnamgjdctvfs
        ///bqlporuexkwyyahnbmgjdctvfb
        ///bqlhoruexkwzyahefmgjdctvfs
        ///bqlporuegkwzyahdimgodctvfs
        ///bqlporuxxkwhybhnimgjdctvfs
        ///dqlporuexkwzyahnimgjfcivfs
        ///bqlporlexkwzyarniigjdctvfs
        ///bqlporuezkqzeahnimgjdctvfs
        ///bqlporuefkwzyamnsmgjdctvfs
        ///bqlporuexkwzyahqimgjdazvfs
        ///bqspocuexkwzyahnimgjdctffs
        ///bqlporuexkwzywhnimgjiccvfs
        ///bqlcoruexkwzyahnimgjdgtvfj
        ///bqljoruexkwvyahnimgcdctvfs
        ///bqeporuexkwzyahnionjdctvfs
        ///bqlporuexkwzyabnxmgjqctvfs
        ///bqjporuexkwzyahnimtddctvfs
        ///bqlprruexkezyahbimgjdctvfs
        ///bqlporue [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DAY02 {
            get {
                return ResourceManager.GetString("DAY02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1 @ 935,649: 22x22
        ///#2 @ 346,47: 19x26
        ///#3 @ 218,455: 25x17
        ///#4 @ 451,711: 10x20
        ///#5 @ 797,342: 28x27
        ///#6 @ 97,281: 23x13
        ///#7 @ 752,418: 25x26
        ///#8 @ 181,975: 11x20
        ///#9 @ 986,373: 13x18
        ///#10 @ 734,260: 21x18
        ///#11 @ 174,822: 15x14
        ///#12 @ 339,138: 20x28
        ///#13 @ 190,315: 20x14
        ///#14 @ 890,631: 26x29
        ///#15 @ 967,390: 16x10
        ///#16 @ 314,205: 10x23
        ///#17 @ 199,93: 14x20
        ///#18 @ 965,143: 19x29
        ///#19 @ 876,70: 15x18
        ///#20 @ 671,254: 11x25
        ///#21 @ 755,229: 14x18
        ///#22 @ 578,727: 24x14
        ///#23 @ 298,459: 11x25
        ///#24 @ 593,793: 25x2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DAY03 {
            get {
                return ResourceManager.GetString("DAY03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1518-11-22 00:00] Guard #1231 begins shift
        ///[1518-04-13 00:00] falls asleep
        ///[1518-09-09 00:02] falls asleep
        ///[1518-04-06 00:58] wakes up
        ///[1518-04-28 00:19] falls asleep
        ///[1518-03-25 00:52] wakes up
        ///[1518-04-12 00:56] falls asleep
        ///[1518-10-25 00:09] falls asleep
        ///[1518-09-07 00:00] Guard #2383 begins shift
        ///[1518-08-20 00:17] falls asleep
        ///[1518-05-09 00:58] wakes up
        ///[1518-05-16 00:16] falls asleep
        ///[1518-08-25 23:57] Guard #3499 begins shift
        ///[1518-10-09 00:51] falls asleep
        ///[1518-10-04 00:53] wakes u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DAY04 {
            get {
                return ResourceManager.GetString("DAY04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vVuyYJjUzzZPxXqQpZmgGMvNmMyYTtnVkWwKVvOosmTtMSkDdKFsSpEePhXEexzZtnNTHEeGoOmMRrGggfnSsNwWVvJGgFEefpPMmeUuEoOBbjJuUwWjhHUMmjYyJsGgiISEepjJGgPZQqoOzyKkvVWXxhpPFcCfreESsjJRHUCcXGyYgQXxCcqXfFvVcCLlxxuwMmzZkEeoOKHhHLzZFflhiIOoHhjJaAJjYyHJjhmMYUwSsWUNxXUuFfuKkbBUtTnJjuNeEYyTxXtYyeIixXsvVQqSbBrRIifIpwIFfiWPiFEnaPFAafkKaKkAFfptTTtACHhWwcKkBbwgLlfFGWPUuJiIZFfznNjvVpSAaQqsnRrOojJsdmMDSVvRfFWvVwhaAHrwWUyYugAqQqQaGEexIiXVWwvbcCcCOaAoqQBLlNtEsSyYntTNeTHhZnNzJjSsCcWgGjJwzeEZaqQHtThALlBbnNJHhjbGgRrBPrReUcmPpMqQCuWwNnELlfzH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DAY05 {
            get {
                return ResourceManager.GetString("DAY05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step I must be finished before step G can begin.
        ///Step J must be finished before step A can begin.
        ///Step L must be finished before step D can begin.
        ///Step V must be finished before step S can begin.
        ///Step U must be finished before step T can begin.
        ///Step F must be finished before step Z can begin.
        ///Step D must be finished before step A can begin.
        ///Step E must be finished before step Z can begin.
        ///Step C must be finished before step Q can begin.
        ///Step H must be finished before step X can begin.
        ///Step A must  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DAY07 {
            get {
                return ResourceManager.GetString("DAY07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 11 6 2 5 3 3 5 1 5 0 10 8 3 4 1 4 1 8 8 4 8 3 1 3 3 1 1 7 0 6 5 1 9 4 1 6 1 3 2 3 1 2 2 1 7 0 10 8 7 3 2 5 6 1 3 6 1 2 3 2 3 1 1 3 2 2 5 2 5 3 6 1 7 0 7 6 4 1 7 7 6 7 2 2 1 3 1 1 1 1 9 0 10 6 2 1 9 1 8 1 1 2 5 1 3 1 1 1 1 2 3 3 1 9 0 7 6 1 8 6 3 7 5 3 3 3 1 2 2 2 1 1 5 1 3 5 1 1 3 7 1 6 0 11 4 4 5 3 7 1 7 8 8 8 8 3 1 1 3 2 3 1 9 0 6 5 1 1 9 3 5 2 3 3 1 3 2 3 2 2 1 7 0 10 4 9 5 4 9 7 8 1 8 8 1 1 1 1 1 2 1 1 4 4 4 5 2 2 3 4 1 6 0 11 9 4 1 3 4 1 3 8 9 2 8 2 3 1 2 2 2 1 6 0 9 9 8 5 1 8 1 9 1 6 1 1 1 1 1 1 1 7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DAY08 {
            get {
                return ResourceManager.GetString("DAY08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 465 players; last marble is worth 71940 points.
        /// </summary>
        internal static string DAY09 {
            get {
                return ResourceManager.GetString("DAY09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +11
        ///+16
        ///+2
        ///-16
        ///-6
        ///+13
        ///-6
        ///-8
        ///-17
        ///+15
        ///-11
        ///-14
        ///+17
        ///-9
        ///+4
        ///+1
        ///-15
        ///-17
        ///-8
        ///+16
        ///+6
        ///-11
        ///-15
        ///-2
        ///+3
        ///-6
        ///-2
        ///-4
        ///-2
        ///-18
        ///-6
        ///-2
        ///+18
        ///-4
        ///+7
        ///+15
        ///-11
        ///+8
        ///-4
        ///-17
        ///-19
        ///-15
        ///-17
        ///-7
        ///+12
        ///-2
        ///-5
        ///-13
        ///-4
        ///-13
        ///-18
        ///+16
        ///+12
        ///+10
        ///+14
        ///-19
        ///+13
        ///+10
        ///+8
        ///-10
        ///+3
        ///-16
        ///-7
        ///-9
        ///-19
        ///-15
        ///-19
        ///+2
        ///+7
        ///-1
        ///+7
        ///+1
        ///-20
        ///-5
        ///-10
        ///+14
        ///+10
        ///+5
        ///+13
        ///+10
        ///+15
        ///+3
        ///-16
        ///-17
        ///+19
        ///+15
        ///+2
        ///+14
        ///-11
        ///+3
        ///-11
        ///-17
        ///-8
        ///+16
        ///-13
        ///-1
        ///+16
        ///+1
        ///+12
        ///-5
        ///+20
        ///+16
        ///+10
        ///-9
        ///-8
        ///+15
        ///-4
        ///+3
        ///+5
        ///+7
        ///+1
        ///-2
        ///+19 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DAY1 {
            get {
                return ResourceManager.GetString("DAY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ** Advent of Code 2018 **
        ///** @mrzepisko
        ///
        ///.
        /// </summary>
        internal static string HELLO_WORLD {
            get {
                return ResourceManager.GetString("HELLO_WORLD", resourceCulture);
            }
        }
    }
}
