//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2018 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2018.InputResource", typeof(InputResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bqlpzruexkszyahnamgjdctvfs
        ///bqlporuexkwyyahnbmgjdctvfb
        ///bqlhoruexkwzyahefmgjdctvfs
        ///bqlporuegkwzyahdimgodctvfs
        ///bqlporuxxkwhybhnimgjdctvfs
        ///dqlporuexkwzyahnimgjfcivfs
        ///bqlporlexkwzyarniigjdctvfs
        ///bqlporuezkqzeahnimgjdctvfs
        ///bqlporuefkwzyamnsmgjdctvfs
        ///bqlporuexkwzyahqimgjdazvfs
        ///bqspocuexkwzyahnimgjdctffs
        ///bqlporuexkwzywhnimgjiccvfs
        ///bqlcoruexkwzyahnimgjdgtvfj
        ///bqljoruexkwvyahnimgcdctvfs
        ///bqeporuexkwzyahnionjdctvfs
        ///bqlporuexkwzyabnxmgjqctvfs
        ///bqjporuexkwzyahnimtddctvfs
        ///bqlprruexkezyahbimgjdctvfs
        ///bqlporue [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DAY02 {
            get {
                return ResourceManager.GetString("DAY02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +11
        ///+16
        ///+2
        ///-16
        ///-6
        ///+13
        ///-6
        ///-8
        ///-17
        ///+15
        ///-11
        ///-14
        ///+17
        ///-9
        ///+4
        ///+1
        ///-15
        ///-17
        ///-8
        ///+16
        ///+6
        ///-11
        ///-15
        ///-2
        ///+3
        ///-6
        ///-2
        ///-4
        ///-2
        ///-18
        ///-6
        ///-2
        ///+18
        ///-4
        ///+7
        ///+15
        ///-11
        ///+8
        ///-4
        ///-17
        ///-19
        ///-15
        ///-17
        ///-7
        ///+12
        ///-2
        ///-5
        ///-13
        ///-4
        ///-13
        ///-18
        ///+16
        ///+12
        ///+10
        ///+14
        ///-19
        ///+13
        ///+10
        ///+8
        ///-10
        ///+3
        ///-16
        ///-7
        ///-9
        ///-19
        ///-15
        ///-19
        ///+2
        ///+7
        ///-1
        ///+7
        ///+1
        ///-20
        ///-5
        ///-10
        ///+14
        ///+10
        ///+5
        ///+13
        ///+10
        ///+15
        ///+3
        ///-16
        ///-17
        ///+19
        ///+15
        ///+2
        ///+14
        ///-11
        ///+3
        ///-11
        ///-17
        ///-8
        ///+16
        ///-13
        ///-1
        ///+16
        ///+1
        ///+12
        ///-5
        ///+20
        ///+16
        ///+10
        ///-9
        ///-8
        ///+15
        ///-4
        ///+3
        ///+5
        ///+7
        ///+1
        ///-2
        ///+19 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DAY1 {
            get {
                return ResourceManager.GetString("DAY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ** Advent of Code 2018 **
        ///** @mrzepisko
        ///
        ///.
        /// </summary>
        internal static string HELLO_WORLD {
            get {
                return ResourceManager.GetString("HELLO_WORLD", resourceCulture);
            }
        }
    }
}
